Models/Character.cs
using Newtonsoft.Json.Linq;

namespace NicasourceAssessment.Models
{
    public class Character : CharacterSearch
    {
        public string FullName {get; set;}
        public string FirstAppearance {get; set;}
        public JObject PowerStats {get; set;}
        public JObject Appeareance {get; set;}
        public JObject Biography {get; set;}

    }
}

Models/CharacterSearch.cs
namespace NicasourceAssessment.Models
{
    public class CharacterSearch
    {
        public string Response {get; set;}
        public string Id {get; set;}
        public string ImageURL {get; set;}
        public string Name {get; set;}
        public string Gender {get; set;}
    }
}

Models/ErrorViewModel.cs
using System;

namespace NicasourceAssessment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Search.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace NicasourceAssessment.Models
{
    public class Search
    {
        private static readonly HttpClient client = new HttpClient();
        [JsonInclude]
        public JObject FormattedResponse {get; set;}
        public string SearchURL {get; set;}
        public Task<JObject> JsonSearchResultFormatted;

        public Search(string SearchURL)
        {
            this.SearchURL = SearchURL;
            FormattedResponse = GetFormattedResponse();
        }

        public JObject GetFormattedResponse()
        {
            JsonSearchResultFormatted = Task.Run( () => GetSearchResponse(this.SearchURL));
            JsonSearchResultFormatted.Wait();
            return JsonSearchResultFormatted.Result;
        }

        public async Task<JObject> GetSearchResponse(string SearchURL)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var streamTask = await client.GetStringAsync(SearchURL);
            var msg = streamTask.ToString();
            return JObject.Parse(msg);
        }
    }
}

Models/SearchResult.cs
using Newtonsoft.Json.Linq;
using NicasourceAssessment.Models;

namespace NicasourceAssessment.Models
{
    public class SearchResult
    {
        public bool IsSearchResult {get; set;}
        public SearchResult(bool IsSearchResult)
        {
            this.IsSearchResult = IsSearchResult;
        }

    }
}

Controllers/CharacterController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using NicasourceAssessment.Models;
using Newtonsoft.Json.Linq;

namespace NicasourceAssessment.Controllers
{
    public class CharacterController : Controller
    {   
        public Search SearchObject;
        public IActionResult Index()
        {
            return View();
        }

        [Route("Character/{CharacterID?}")]
        [Route("Character/Index/{CharacterID?}")]
        public IActionResult Index(int CharacterID)
        {
            string URL = "https://superheroapi.com/api/4368073683252121/" + CharacterID;
            SearchObject = new Search(URL);
            if (SearchObject.FormattedResponse["response"].ToString().Equals("success"))
            {
                Character SearchedCharacter = new Character();
                SearchedCharacter.Id = SearchObject.FormattedResponse["id"].ToString();
                SearchedCharacter.Name = SearchObject.FormattedResponse["name"].ToString();
                SearchedCharacter.FullName = SearchObject.FormattedResponse["biography"]["full-name"].ToString();
                SearchedCharacter.FirstAppearance = SearchObject.FormattedResponse["biography"]["first-appearance"].ToString();
                SearchedCharacter.ImageURL = SearchObject.FormattedResponse["image"]["url"].ToString();
                SearchedCharacter.PowerStats = (JObject) SearchObject.FormattedResponse["powerstats"];
                SearchedCharacter.Appeareance = (JObject) SearchObject.FormattedResponse["appearance"];
                SearchedCharacter.Biography = (JObject) SearchObject.FormattedResponse["biography"];
                return View(SearchedCharacter);
            }
            else
                return View("Error");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using NicasourceAssessment.Models;

namespace NicasourceAssessment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public static readonly HttpClient client = new HttpClient();
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.IsSearchResult = false;
            List<CharacterSearch> EmptyObject = new List<CharacterSearch>();
            return View(EmptyObject);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpPost]
        public ActionResult Index(string SearchCriteria)
        {
            string URL = "https://superheroapi.com/api/4368073683252121/search/" + SearchCriteria;
            Search SearchObject = new Search(URL);
            SearchResult searchResult = new SearchResult(true);
            ViewBag.IsSearchResult = false;
            List<CharacterSearch> Character = new List<CharacterSearch>();
            if (SearchObject.FormattedResponse["response"].ToString().Equals("success")) 
            {    
                ViewBag.IsSearchResult = true;
                foreach(JObject CharacterInfo in SearchObject.FormattedResponse["results"])
                {
                    Character.Add(
                        new CharacterSearch(){
                            Response = SearchObject.FormattedResponse["results"].ToString(),
                            Id = CharacterInfo["id"].ToString(),
                            ImageURL = CharacterInfo["image"]["url"].ToString(),
                            Name = CharacterInfo["name"].ToString(),
                            Gender = CharacterInfo["appearance"]["gender"].ToString()
                        }
                    );
                }  
            }
            return View(Character);
        }
    }
}

Views/Character/Index.cshtml
@model Character;

@{
    ViewData["Title"] = "Character information";
}

<div class="text-center">
    <h1>@Model.Name</h1>
    <br/>
    <div class="container">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="@Model.ImageURL" alt="Admin" class="" width="150">
                    <div class="mt-3">
                      <h4>@Model.Name</h4>
                      <p class="text-secondary mb-1">@Model.Appeareance["gender"]</p>
                      <p class="text-muted font-size-sm">@Model.Appeareance["race"]</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      @Model.Biography["full-name"]
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Alter egos</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      @Model.Biography["alter-egos"]
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Place of birth</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      @Model.Biography["place-of-birth"]
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Appearance</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      @Model.Biography["first-appearance"]
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Publisher</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      @Model.Biography["publisher"]
                    </div>
                  </div>
                  <hr>
                </div>
              </div>

              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3">Power Statistics</h6>
                      <small>Intelligence</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["intelligence"]%' aria-valuenow='@Model.PowerStats["intelligence"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Strength</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["strength"]%' aria-valuenow='@Model.PowerStats["strength"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Speed</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["speed"]%' aria-valuenow='@Model.PowerStats["speed"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Durability</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["durability"]%' aria-valuenow='@Model.PowerStats["durability"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Power</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["power"]%' aria-valuenow='@Model.PowerStats["power"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Combat</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style='width: @Model.PowerStats["combat"]%' aria-valuenow='@Model.PowerStats["combat"]' aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    </div>

</div>

Views/Home/Index.cshtml
@model List<CharacterSearch>;

@{
    ViewData["Title"] = "Search your SuperHero";
}

<div class="text-center">
    <div class="col-lg-12"></div>
        <h1>Search your SuperHero here!</h1>
        <br/>
        <form asp-controller="Home" asp-action="Index">
            <input type="text" name="SearchCriteria" />
            <input type="submit" value="Search!"/>
        </form>
    </div>
    <br/>

@if (@ViewData["IsSearchResult"].Equals(true))
{
<div class="event-schedule-area-two bg-color pad100 col-lg-12">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="text-center" scope="col">Id</th>
                                        <th scope="col">Image</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Gender</th>
                                        <th class="text-center" scope="col">Full profile</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(var CharacterInfo in Model)
                                    {

                
                                    <tr class="inner-box">
                                        <th scope="row">
                                            <div class="event-date">
                                                <p>@CharacterInfo.Id</p>
                                            </div>
                                        </th>
                                        <td>
                                            <div class="event-img">
                                                <img src="@CharacterInfo.ImageURL" alt="" />
                                            </div>
                                        </td>
                                        <td>
                                            <div class="event-wrap">
                                                <h3><a onclick="location.href='@Url.Action("Index", "Character", new {CharacterID = "" + @CharacterInfo.Id})'">@CharacterInfo.Name</a></h3>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="r-no">
                                                <span>@CharacterInfo.Gender</span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="primary-btn">
                                                <a class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Character", new {CharacterID = "" + @CharacterInfo.Id})'">Read More</a>
                                            </div>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
</div>
}
</div>

Views/Home/SearchResult.cshtml
<p>Hola mundo</p>

Views/Shared/CommonLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nicasource Assessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Nicasource Assessment - Christhofer Gutierrez
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NicasourceAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NicasourceAssessment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NicasourceAssessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>